#ifndef CARDSDATA_H
#define CARDSDATA_H

#include <QString>

struct Card {
    QString code;
    QString type;
    QString category;
    QString color;
    QString image;
    QString description;
};

constexpr int CARDS_NUMBER = 94;

const Card CARDS_DATA[CARDS_NUMBER] = {
    {"C001", "Minieuro", "Era X",      "Red",      "c001.jpg", "Pay 2 Energy Points to execute a Travel operation with your Champion in any region. Your other units cannot Travel."},
    {"C002", "Minieuro", "Era X",      "Red",      "c002.jpg", "Pay 2 Energy Points to gain 2 Experience Points and perform the Develop action."},
    {"C003", "Minieuro", "Era X",      "Red",      "c003.jpg", "Pay 2 Energy Points to Act."},
    {"C004", "Minieuro", "Era X",      "Red",      "c004.jpg", "Pay 2 Energy Points to Start a Battle in any region with at least 1 Opponent and add 2 to your Strength. It doesn't matter if your Artefact tile is turned discharged side or charged side up (if it is charged side up, don't turn it discharged side up)."},
    {"C005", "Minieuro", "Era X",      "Red",      "c005.jpg", "Pay 2 Energy Points to Meditate."},
    {"C006", "Minieuro", "Era X",      "Yellow",   "c006.jpg", "Pay 2 Energy Points to gain 3 Glory Points for each Forest you control."},
    {"C007", "Minieuro", "Era X",      "Yellow",   "c007.jpg", "Pay 2 Energy Points to gain 3 Glory Points for each Land of Mist you control."},
    {"C008", "Minieuro", "Era X",      "Yellow",   "c008.jpg", "Pay 2 Energy Points to gain 3 Glory Points for each River you control."},
    {"C009", "Minieuro", "Era X",      "Yellow",   "c009.jpg", "Pay 2 Energy Points to gain 3 Glory Points for each Crystal Field you control."},
    {"C010", "Minieuro", "Era X",      "Yellow",   "c010.jpg", "Pay 2 Energy Points to gain 3 Glory Points for each Mountain you control."},
    {"C011", "Minieuro", "Era X",      "Green",    "c011.jpg", "Discard 1 Tactic Card to Act."},
    {"C012", "Minieuro", "Era X",      "Green",    "c012.jpg", "Discard 1 Objective Card to Develop."},
    {"C013", "Minieuro", "Era X",      "Green",    "c013.jpg", "Discard 1 Accessory Card to Meditate."},
    {"C014", "Minieuro", "Era X",      "Green",    "c014.jpg", "Discard 1 Development Card to Recharge your Artefact and gain 4 Glory Points. You can also choose only one of the two effects."},
    {"C015", "Minieuro", "Era X",      "Green",    "c015.jpg", "Discard 1 any Card to gain X Command Points, where X is equal to the number of Command Points of the discarded card (you must spend immediately the gained Command Points)."},
    {"C016", "Minieuro", "Era X",      "Blue",     "c016.jpg", "As long as this card is on your player board, when you Deploy a Fortification, you may deploy it in any region (also in regions where you are not present)."},
    {"C017", "Minieuro", "Era X",      "Blue",     "c017.jpg", "As long as this card is on your playerboard, when you Deploy 1 Troop, you may gain 1 Experience Point."},
    {"C018", "Minieuro", "Era X",      "Blue",     "c018.jpg", "As long as this card is on your playerboard, when you Recruit 1 Golem, you may Deploy it at no cost."},
    {"C019", "Minieuro", "Era X",      "Blue",     "c019.jpg", "As long as this card is on your playerboard, add 2 to the Strengh of your Champion."},
    {"C020", "Minieuro", "Era X",      "Blue",     "c020.jpg", "As long as this card is on your playerboard, when you play a Development Card, you won't have to spend its placing cost."},
    {"C021", "Minieuro", "Era I",      "Red",      "c021.jpg", "Pay 1 Energy Point to Recharge your Artefact."},
    {"C022", "Minieuro", "Era I",      "Red",      "c022.jpg", "Pay 1 Energy Point to execute a Travel operation with 1 Golem to any region (also in regions where you are not present). The Golem cannot carry any unit."},
    {"C023", "Minieuro", "Era I",      "Red",      "c023.jpg", "Pay 2 Energy Points to choose any region and remove 1 Fortification from each Opponent present in that region."},
    {"C024", "Minieuro", "Era I",      "Red",      "c024.jpg", "Pay 3 Energy Points to Recruit 1 Troop and 1 Golem. You can also choose only one of two effects."},
    {"C025", "Minieuro", "Era I",      "Red",      "c025.jpg", "Pay 3 Energy Points to Deploy 1 Troop and 1 Golem. You can also choose only one of two effects."},
    {"C026", "Minieuro", "Era I",      "Yellow",   "c026.jpg", "Pay 1 Energy Point to gain 3 Glory Points."},
    {"C027", "Minieuro", "Era I",      "Yellow",   "c027.jpg", "Pay 1 Energy Point and remove from the game 1 Tactic Card to gain X Command Points and X Experience Points, where X is equal to the number of Command Points of the removed Tactic Card."},
    {"C028", "Minieuro", "Era I",      "Yellow",   "c028.jpg", "Pay 2 Energy Points to gain 2 Glory Points for each of your Fortifications currently deployed."},
    {"C029", "Minieuro", "Era I",      "Yellow",   "c029.jpg", "Pay 3 Energy Points to gain 1 Glory Point and 1 Energy Point, for each of your Golems currently deployed."},
    {"C030", "Minieuro", "Era I",      "Yellow",   "c030.jpg", "Pay 3 Energy Points to gain 3 Glory Points for each Encounter you have faced."},
    {"C031", "Minieuro", "Era I",      "Green",    "c031.jpg", "Pay 0 Energy Points to gain 1 Energy Point."},
    {"C032", "Minieuro", "Era I",      "Green",    "c032.jpg", "Pay 1 Energy Point to execute a Travel operation with your Champion to any region (also in regions where you are not present). The Champion cannot carry any unit."},
    {"C033", "Minieuro", "Era I",      "Green",    "c033.jpg", "Pay 1 Energy Point to gain 2 Glory Points."},
    {"C034", "Minieuro", "Era I",      "Green",    "c034.jpg", "Pay 1 Energy Point to Recruit 1 Golem, or execute a Travel operation with 1 Golem."},
    {"C035", "Minieuro", "Era I",      "Green",    "c035.jpg", "Pay 1 Energy Point to Recruit or execute a Travel operation with 1 Troop."},
    {"C036", "Minieuro", "Era I",      "Blue",     "c036.jpg", "As long as this card is on your playerboard, when you Deploy 1 Fortification, you may gain 1 Experience Point."},
    {"C037", "Minieuro", "Era I",      "Blue",     "c037.jpg", "As long as this card is on your playerboard, when you Deploy 1 Golem, you may gain 3 Glory Points."},
    {"C038", "Minieuro", "Era I",      "Blue",     "c038.jpg", "As long as this card is on your player board, when your Champion Travels, you may carry 1 of any unit. The carried unit has to start in the same region as your Champion. (You cannot carry a unit that has already Travelled this turn. If your Champion Travels several times, you can carry a different unit each time.)"},
    {"C039", "Minieuro", "Era I",      "Blue",     "c039.jpg", "As long as this card is on your playerboard, when you Recruit 1 Troop, you may Deploy it without cost."},
    {"C040", "Minieuro", "Era I",      "Blue",     "c040.jpg", "As long as this card is on your playerboard, when you play a Accessory Card, you won't have to spend its placing cost."},
    {"C041", "Minieuro", "Era II",     "Red",      "c041.jpg", "Pay 1 Energy Point to draw up to 2 cards from the top of Command Deck of the current Era at no cost."},
    {"C042", "Minieuro", "Era II",     "Red",      "c042.jpg", "Pay 2 Energy Points to execute a Travel operation with up to 2 Troops to any region (also in regions where you are not present). The Troops cannot carry any units. The 2 Troops can Travel to 2 different regions, independently."},
    {"C043", "Minieuro", "Era II",     "Red",      "c043.jpg", "Pay 3 Energy Points to Start a Battle in any region with at least 1 Opponent and add 3 to your Stength. (To perform this effect your Artefact keeps the current state. The Artefact does not discharge.)"},
    {"C044", "Minieuro", "Era II",     "Red",      "c044.jpg", "Pay 3 Energy Points to choose any region and remove 1 Troop for each Opponent present from the region."},
    {"C045", "Minieuro", "Era II",     "Red",      "c045.jpg", "Pay 4 Energy Points to choose a region and execute a Travel operation with all the units from that region to any other region (also in a region where you are not present). Units that have already Traveled this turn cannot Travel again."},
    {"C046", "Minieuro", "Era II",     "Yellow",   "c046.jpg", "Pay 1 Energy Point and remove from the game 1 Objective Card to gain X Glory Points and X Command Points, where X is equal to the number of Command Points of the removed Objective Card."},
    {"C047", "Minieuro", "Era II",     "Yellow",   "c047.jpg", "Pay 2 Energy Points to gain 5 Glory Points."},
    {"C048", "Minieuro", "Era II",     "Yellow",   "c048.jpg", "Pay 3 Energy Points to gain 7 Glory Points."},
    {"C049", "Minieuro", "Era II",     "Yellow",   "c049.jpg", "Pay 3 Energy Points to gain 1 Glory Point for each Troop currently deployed ."},
    {"C050", "Minieuro", "Era II",     "Yellow",   "c050.jpg", "Pay 4 Energy Points to gain 2 Glory Points for each Island where you are with at least 1 unit."},
    {"C051", "Minieuro", "Era II",     "Green",    "c051.jpg", "Pay 0 Energy Points to gain 1 Experience Point and 1 Glory Point."},
    {"C052", "Minieuro", "Era II",     "Green",    "c052.jpg", "Pay 1 Energy Point to Recruit or Deploy 1 Golem."},
    {"C053", "Minieuro", "Era II",     "Green",    "c053.jpg", "Pay 1 Energy Point to Recruit or Deploy 1 Troop."},
    {"C054", "Minieuro", "Era II",     "Green",    "c054.jpg", "Pay 1 Experience Point to gain 4 Glory Points."},
    {"C055", "Minieuro", "Era II",     "Green",    "c055.jpg", "Pay 1 Energy Point to Deploy 1 Fortification."},
    {"C056", "Minieuro", "Era II",     "Blue",     "c056.jpg", "As long as this card is on your playerboard, when you Deploy 1 unit, you may Deploy it in any region of the Island where your Champion is."},
    {"C057", "Minieuro", "Era II",     "Blue",     "c057.jpg", "As long as this card is on your playerboard, when you play a Tactic Card, you won't have to spend its Energy cost."},
    {"C058", "Minieuro", "Era II",     "Blue",     "c058.jpg", "As long as this card is on your playerboard, add 1 to the Strengh of your Golems."},
    {"C059", "Minieuro", "Era II",     "Blue",     "c059.jpg", "As long as this card is on your player board, when 1 Troop Travels, it can carry another unit to the same region. The carried unit has to start in the same region as your Troop. (You cannot carry a unit that has already Traveled this turn.)"},
    {"C060", "Minieuro", "Era II",     "Blue",     "c060.jpg", "As long as this card is on your playerboard, add 1 to the Strengh of your Fortifications."},
    {"C061", "Minieuro", "Era III",    "Red",      "c061.jpg", "Pay 1 Energy Point to gain 12 Energy Points."},
    {"C062", "Minieuro", "Era III",    "Red",      "c062.jpg", "Pay 2 Energy Points to choose any region and remove 1 Golem from each Opponent present in that region."},
    {"C063", "Minieuro", "Era III",    "Red",      "c063.jpg", "Pay 3 Energy Points to choose a Monster. You can only choose a Monster whose card has already been placed in the Event Board during this Era. The chosen Monster attacks immediately."},
    {"C064", "Minieuro", "Era III",    "Red",      "c064.jpg", "Pay 4 Energy Points to wound 1 Champion from each Opponent present in that region."},
    {"C065", "Minieuro", "Era III",    "Red",      "c065.jpg", "Pay 5 Energy Points to Start a Battle in any region with at least 1 Opponent and add 5 to your Stength. (To perform this effect your Artefact keeps the current state. The Artefact does not discharge.)"},
    {"C066", "Minieuro", "Era III",    "Yellow",   "c066.jpg", "Pay 1 Energy Point and remove from the game 1 Accessory Card to gain X Energy Points and X Glory Points, where X is equal to the number of Command Points of the removed Accessory Card."},
    {"C067", "Minieuro", "Era III",    "Yellow",   "c067.jpg", "Pay 1 Energy Point and remove from the game 1 Development Card to gain X Glory Points and X Experience Points, where X is equal to the number of Command Points of the removed Development Card."},
    {"C068", "Minieuro", "Era III",    "Yellow",   "c068.jpg", "Pay 2 Energy Points and Discharge your Artefact to gain 13 Glory Points."},
    {"C069", "Minieuro", "Era III",    "Yellow",   "c069.jpg", "Pay 4 Energy Points to gain 9 Glory Points."},
    {"C070", "Minieuro", "Era III",    "Yellow",   "c070.jpg", "Pay 5 Energy Points and remove from the game 1 Development Card, 1 Accessory Card, 1 Objective Card and 1 Tactic Card to gain 16 glory Points."},
    {"C071", "Minieuro", "Era III",    "Green",    "c071.jpg", "Discharge your Artefact to choose a Monster or Meditate twice. You can only choose a Monster whose its card has already been placed in the Event Board during this Era. The chosen Monster attacks immediately."},
    {"C072", "Minieuro", "Era III",    "Green",    "c072.jpg", "Pay 1 Energy Point to Deploy 1 Golem or execute a Travel operation with 1 Golem."},
    {"C073", "Minieuro", "Era III",    "Green",    "c073.jpg", "Pay 1 Energy Point to Deploy 1 Troop or execute a Travel operation with 1 Troop."},
    {"C074", "Minieuro", "Era III",    "Green",    "c074.jpg", "Pay 1 Experience Point to gain 6 Glory Points."},
    {"C075", "Minieuro", "Era III",    "Green",    "c075.jpg", "Discard 1 any Card to gain two times X Glory Points, where X is equal to the number of Command Points of the discarded Card."},
    {"C076", "Minieuro", "Era III",    "Blue",     "c076.jpg", "As long as this card is on your playerboard, add 3 to the Strengh of your Champion."},
    {"C077", "Minieuro", "Era III",    "Blue",     "c077.jpg", "As long as this card is on your player board, when 1 Golem Travels, it can carry another unit to the same region. The carried unit has to start in the same region as your Golem. (You cannot carry a unit that has already Traveled this turn.)"},
    {"C078", "Minieuro", "Era III",    "Blue",     "c078.jpg", "As long as this card is on your playerboard, when you play a Objective Card, you won't have to spend its Energy cost."},
    {"C079", "Minieuro", "Era III",    "Blue",     "c079.jpg", "As long as this card is on your playerboard, when you Deploy 1 Fortification, you may gain 4 Glory Points."},
    {"C080", "Minieuro", "Era III",    "Blue",     "c080.jpg", "As long as this card is on your playerboard, add 1 to the Strengh of your Troops."},
    {"H01",  "Poker",    "Hero",       "Gray",     "h01.jpg",  "When you start a Battle in the region where Anuth is, or if Anuth is in an island attacked by a Monster, Anuth receive 3 Strength Points until the end of the Battle or Monster attack."},
    {"H02",  "Poker",    "Hero",       "Gray",     "h02.jpg",  "When Celethe is on an island attacked by a Monster, if the Monster loses, the player holding Celethe doubles their reward."},
    {"H03",  "Poker",    "Hero",       "Gray",     "h03.jpg",  "When you Start a Battle, yout receive 1 extra Glory Point for each unit, including your and enemy units, that is removed or retreats."},
    {"H04",  "Poker",    "Hero",       "Gray",     "h04.jpg",  "At the beginning of each Era, you will receive 4 extra Energy Points. If Telron is wounded, you won't receive the 4 extra Energy Points at the beginning of the next Era."},
    {"A01",  "Poker",    "Attunement", "Gray",     "a01.jpg",  "When you attune to the illustrated anomaly, receive 3 Glory Points for each Development card in play on your player board."},
    {"A02",  "Poker",    "Attunement", "Gray",     "a02.jpg",  "When you attune to the illustrated anomaly, receive 4 Glory Points for each Encounter card you have faced."},
    {"A03",  "Poker",    "Attunement", "Gray",     "a03.jpg",  "When you attune to the illustrated anomaly, receive 3 Glory Points for each region you control."},
    {"A04",  "Poker",    "Attunement", "Gray",     "a04.jpg",  "When you attune to the illustrated anomaly, receive 2 Glory Points for each Troop you have placed."},
    {"A05",  "Poker",    "Attunement", "Gray",     "a05.jpg",  "When you attune to the illustrated anomaly, receive 2 Glory Points for each card in your pile."},
    {"A06",  "Poker",    "Attunement", "Gray",     "a06.jpg",  "When you attune to the illustrated anomaly, receive 4 Glory Points for each Accessory card in play on your player board."},
    {"A07",  "Poker",    "Attunement", "Gray",     "a07.jpg",  "When you attune to the illustrated anomaly, receive 2 Glory Points for each Experience you have had."},
    {"A08",  "Poker",    "Attunement", "Gray",     "a08.jpg",  "When you attune to the illustrated anomaly, receive 1 Glory Point for each region where you have at least one unit."},
    {"A09",  "Poker",    "Attunement", "Gray",     "a09.jpg",  "When you attune to the illustrated anomaly, receive 3 Glory Points for each Golem you have deployed."},
    {"A10",  "Poker",    "Attunement", "Gray",     "a10.jpg",  "When you attune to the illustrated anomaly, at the end of this Era, receive 8 Glory Points for each Monster defeated (even if you didn't take part in the attack)."},
};

#endif // CARDSDATA_H
